"""The Legend of Tecla reimplementado en Python."""

from .ai import AccionIA, ControladorIA, PercepcionIA, TipoAccionIA, controlador_para
from .commands import Comando, ParserComandos, RegistroComandos
from .completeness import EQUIVALENCIAS, EquivalenciaModulo, auditoria_paridad, paridad_cerrada
from .effects import Fuego, GestorEstados, Inspirado, Mojado
from .engine import MotorTurnos, ResultadoAccion, SistemaCombate, SistemaFuego, SistemaInventario, SistemaMovimiento, SistemaTrampas
from .events import BusEventos, EventoJuego, RegistroEventos, TipoEvento
from .exceptions import AccionInvalidaError, CargaDatosError, TeclaError
from .facade import cargar_partida, crear_partida, crear_partida_desde_config, guardar_partida, sincronizar_logros
from .game import Game, GameConfig, create_game, load_game, save_game
from .hierarchy import (
    AliadoEscuadron,
    Arma,
    Armadura,
    Berserker,
    Binocular,
    Botiquin,
    Commander,
    CommanderPrime,
    Componente,
    Credencial,
    CuboAgua,
    Enemigo,
    Explosivo,
    Floater,
    Francotirador,
    Granada,
    HeavyFloater,
    JERARQUIA_CANONICA,
    Jefe,
    Jugador,
    Linterna,
    Marine,
    Municion,
    Objeto,
    Personaje,
    Sectoid,
    Zapador,
    crear_enemigo,
    crear_jugador,
)
from .model import Difficulty, Direction, Position, VictoryCondition
from .runtime import EntradaHistorial, SesionJuego
from .validation import Limites, Validaciones

__all__ = [
    "AccionIA",
    "AccionInvalidaError",
    "AliadoEscuadron",
    "Arma",
    "Armadura",
    "Berserker",
    "Binocular",
    "Botiquin",
    "BusEventos",
    "CargaDatosError",
    "Comando",
    "Commander",
    "CommanderPrime",
    "Componente",
    "ControladorIA",
    "Credencial",
    "CuboAgua",
    "Difficulty",
    "Direction",
    "EQUIVALENCIAS",
    "Enemigo",
    "EntradaHistorial",
    "EquivalenciaModulo",
    "EventoJuego",
    "Explosivo",
    "Fuego",
    "Floater",
    "Francotirador",
    "Game",
    "GameConfig",
    "GestorEstados",
    "Granada",
    "HeavyFloater",
    "Inspirado",
    "JERARQUIA_CANONICA",
    "Jefe",
    "Jugador",
    "Limites",
    "Linterna",
    "Marine",
    "Mojado",
    "MotorTurnos",
    "Municion",
    "Objeto",
    "ParserComandos",
    "PercepcionIA",
    "Personaje",
    "Position",
    "RegistroComandos",
    "RegistroEventos",
    "ResultadoAccion",
    "Sectoid",
    "SesionJuego",
    "SistemaCombate",
    "SistemaFuego",
    "SistemaInventario",
    "SistemaMovimiento",
    "SistemaTrampas",
    "TeclaError",
    "TipoAccionIA",
    "TipoEvento",
    "Validaciones",
    "VictoryCondition",
    "Zapador",
    "auditoria_paridad",
    "cargar_partida",
    "controlador_para",
    "crear_enemigo",
    "crear_jugador",
    "crear_partida",
    "crear_partida_desde_config",
    "create_game",
    "guardar_partida",
    "load_game",
    "paridad_cerrada",
    "save_game",
    "sincronizar_logros",
]
